import localFont from "next/font/local";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ClientWrapper from "./ClientWrapper";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const plusSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta",
});

export const metadata = {
  title: "Tech-A-Coffee",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" className={`${plusSans.variable} `}>
        <head>
          {/* Favicon */}
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
          <Suspense fallback={<div>Loading...</div>}>
            <ClientWrapper>{children}</ClientWrapper>
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
